# -*- coding: utf-8 -*-
"""FirstSteps.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12Ag7uoUnZd6-HZz2pW-3SK-s2o4KLdG6
"""

print("Ana Pututau")
print("January 14th, 2024")
print("Disciplinary is when you have a single field of study. The main focus of your study is solely focused in a specific domain.")
print("Interdiscipllinary describes a similar approach to your study but intead of a single domain you integrate knowledge from different domains to address the common topic of choice.")

data = """CustomerID|FirstName|LastName|Email
123456|Bob|Smith|bob@smith.com
789012|Sally|Jones|sally@jones.com
345678|Larry|Barnes|larry@barnes.com"""

# Splitting the data into lines
lines = data.split('\n')

for line in lines:
    fields = line.split('|')
    print(fields)

print("To"+" be"+" or"+" not"+" to"+" be")

"""Concatenation is the action used in coding to combine strings together to make one long output.
The difference between the print() function and sep argument is simple,the former is utilized for the end output while the latter is used to seperate strings. End output is used to append add character(s) to the given output.
"""

print(10)
print("Sum:" + str(10 +20))
print(((10 + 20) * 50) / 10)