# -*- coding: utf-8 -*-
"""FirstNotebook

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zqCp50kH7BKaiNQG2HzJIVE_DV2IlzNb

Author: Ana Pututau
Date: 01/14/2024
"""

print("Hello, World!")
print("Hello,", "World!")
print("Hello" + "," + " " + "World" + "!")
print("Hello", "World", sep=", ", end="!")

print("Hello, my name is Ana.")

print("Bob Smith")
print("1234 Nowhere Street")
print("Someplace, UT 84999")
print("(801)555-8888")
print("bob@smithco.com")

print("Wow", "that's great news", sep=",",end="!")

print("111","22","3333", sep="-")